### PR TITLE
added jsfiddle examples

### PR DESCRIPTION
**Pull request by gijscor**
added jsfiddle examples, for students to see the result of what the examples return, and invite them to play with them to see how it really works. This will increase their understanding of the explained topics. @remarcmij would be good to hear your thoughts on the specifics, as you have built this chapter.

### CODE REVIEW

**Comment by remarcmij** [comment]
Actually perhaps the relatively new StackBlitz is an even better alternative and it is VSCode based (of course, not for the HYF application assignment).

Example: https://stackblitz.com/edit/js-wpygdm

**Comment by gijscor** [comment]
@remarcmij I'm quite indifferent towards which platform we use, all look decent. With regards to editing: Not sure if a HYF account is nessesary for changes, you can easily create your own and share your own link (as the examples are really basic), but if requested I can of course make one.

**Comment by gijscor** [comment]
@remarcmij thanks, I'll merge it and also ask the students for some feedback on it. 

One small note, on the last example the javaSCript doesn't "do" anything visible, would you like to change the example so that it actually changes something visible in jsFiddle?

**Comment by remarcmij** [comment]
@gijscor I would like to revise this fundamental more extensively, it's a bit old material. For one thing, in classes I always stress on choosing appropriate names and avoid meaningless names, which includes single letter names. Also names like `foo` and `baz` which are known to experienced developers as deliberately meaning nothing are confusing to beginners.

The HTML in this fundamental, when combined as you did in the fiddle actually produces invalid HTML as you should not append a `li` to a `div` (its parent should be `ul` or `ol`). By trying to run the code in a fiddle such things come to light, which is a good thing.

I'll look into it today.

**Comment by gijscor** [comment]
@remarcmij thanks!

**Pull request merged**
